In [1]:
import scipy 
import numpy as np

In [2]:
from scipy.stats import binom

'[' is not recognized as an internal or external command,
operable program or batch file.


In [8]:
print(binom.pmf(k= 19, n= 25, p = 0.65))

0.09077799859322791


In [9]:
binom.cdf(2,20,0.06)

0.8850275957378545

Solve the binomial probability for n =20, p =40 and x =10

In [12]:
print(binom.pmf(k=10, n=20, p=0.4))

0.11714155053639011


Poisson Distribution

In [13]:
from scipy.stats import poisson

In [14]:
poisson.pmf(3,2) #x=3 , mean =2

0.18044704431548356

Suppose bank customers arrive randomly on weekday afternoons at an average of 3.2 customers every 4 minutes. What is the probability of exactly 5 customers arriving in a 4-minute interval on a weekday afternoon?

In [15]:
poisson.pmf(5,3,2)

0.22404180765538775

Bank customers arrive randomly on weekday afternoons at an average of 3.2 customers every 4 minutes. What is the probability of having more than 7 customers in a 4-min interval on a weekday afternoon? 

In [16]:
prob = poisson.cdf(7,3.2)

In [17]:
prob_more_than_7 = 1-prob
prob_more_than_7

0.01682984174895752

A bank has an average random arrival rate of 3.2 customers every 4 minutes. What is the probability of getting exactly 10 cstomers during an 8-minutes interval?

In [18]:
poisson.pmf(10,6.4)

0.052790043854115495

Uniform Distribution

Suppose the amount of time it takes to assemble a plastic module ranges from 27 to 39 seconds and that assembly times are uniformly distributed. Describe the distribution. What s the probaility that a given assembly will take between 30 and 35 seconds?

In [19]:
U = np.arange(27, 40 , 1)
U

array([27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [20]:
from scipy.stats import uniform
uniform.mean(loc= 27, scale =12)

33.0

In [22]:
uniform.cdf(np.arange(30,36,1), loc =27, scale=12)

array([0.25      , 0.33333333, 0.41666667, 0.5       , 0.58333333,
       0.66666667])

In [23]:
prob = 0.66666667- 0.25
prob

0.41666667

According to the NAtional Association of Insurance Commissioners, the average annual cost for automobile insurance in the United States in a recent yeat was 691. Suppose automobile insurance cost are uniform distributed. US with a range of frim 200 to $1.182. What is the std deviation of this uniform distribution?

In [24]:
uniform.mean(loc = 200, scale = 982)

691.0

In [25]:
uniform.std(loc =200, scale =982)

283.4789821721062

Normal Distribution

In [26]:
from scipy.stats import norm

In [27]:
val,m,s = 68, 65.5, 2.5

In [28]:
print(norm.cdf(val,m,s))

0.8413447460685429


In [29]:
print(1-norm.cdf(val,m,s))

0.15865525393145707


In [30]:
print(norm.cdf((val,m,s)-(norm.cdf(63,m,s))))

[1.         1.         0.99039279]


What is the probability of obtaining a score greater than 7-- on a GMAT test that has a mean of 494 and a standard deviation of 100? Assume GMAt scores are normally distributed.

P(x>700| m = 494 and s = 100) = ?

In [32]:
print(1-norm.cdf(700, 494, 100))

0.019699270409376912


For the same GMAT examination. what is the probaility of randomly drawing sore that is 550 or less?

In [33]:
print(norm.cdf(550,494,100))

0.712260281150973


what is the probaility of randomly obtaining a score between 300 and 600 on the GMAT exam

In [35]:
print(norm.cdf(600,494,100)-norm.cdf((300,494,100)))

[-0.1445723 -0.1445723 -0.1445723]


What is the probability of getting a score between 350 and 450 on the same GMAT exam?

In [36]:
print(norm.cdf(450,494,100)-norm.cdf(350,494,100))

0.2550348541262666


In [37]:
norm.ppf(0.95)

1.6448536269514722

Hyper Geometric Distribution example 

Suppose 18 major computer companies operte in the United States and that 12 are located in Californias Silicon Valley. If three computer companies selected randomly from the entire list , what is the probability that one or more of the selected comapnies are located in the Silicon Valley.


In [38]:
from scipy.stats import hypergeom
pval = hypergeom.sf(0,18,3,12) #hypergeom.sf(x-1,N,n,A), sf = 1-cdf

In [39]:
pval

0.9754901960784306