In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("SampleData.csv")
df

Position  Job Level   Salary
0   Business Analyst          1    30000
1  Junior Consultant          2    50000
2  Senior Consultant          3    60000
3            Manager          4    80000
4    Country Manager          5   110000
5     Region Manager          6   150000
6            Partner          7   200000
7     Senior Partner          8   300000
8            C-level          9   500000
9                CEO         10  1000000

In [4]:
df.head()

Position  Job Level  Salary
0   Business Analyst          1   30000
1  Junior Consultant          2   50000
2  Senior Consultant          3   60000
3            Manager          4   80000
4    Country Manager          5  110000

In [5]:
df.tail()

Position  Job Level   Salary
5  Region Manager          6   150000
6         Partner          7   200000
7  Senior Partner          8   300000
8         C-level          9   500000
9             CEO         10  1000000

In [8]:
df.shape

(10, 3)

In [9]:
df.columns

Index(['Position', 'Job Level', 'Salary'], dtype='object')

In [11]:
df.dtypes

Position     object
Job Level     int64
Salary        int64
dtype: object

In [12]:
df.info

<bound method DataFrame.info of             Position  Job Level   Salary
0   Business Analyst          1    30000
1  Junior Consultant          2    50000
2  Senior Consultant          3    60000
3            Manager          4    80000
4    Country Manager          5   110000
5     Region Manager          6   150000
6            Partner          7   200000
7     Senior Partner          8   300000
8            C-level          9   500000
9                CEO         10  1000000>

In [13]:
df.loc[0]

Position     Business Analyst
Job Level                   1
Salary                  30000
Name: 0, dtype: object

In [14]:
df.iloc[-1]

Position         CEO
Job Level         10
Salary       1000000
Name: 9, dtype: object

In [15]:
df.tail(n=1)

Position  Job Level   Salary
9      CEO         10  1000000

In [16]:
df.iloc[[0,4,5]]

Position  Job Level  Salary
0  Business Analyst          1   30000
4   Country Manager          5  110000
5    Region Manager          6  150000

In [4]:
#Summary of a variable
df['Salary'].describe()

count         10.000000
mean      248000.000000
std       300547.648284
min        30000.000000
25%        65000.000000
50%       130000.000000
75%       275000.000000
max      1000000.000000
Name: Salary, dtype: float64

In [5]:
#Assignment operators
x= 25

In [6]:
x1= "I love India" # storing characters

In [7]:
#Calculate statistical quantities
df['Salary'].mean()


248000.0

In [8]:
df['Salary'].median()

130000.0

In [9]:
df['Salary'].var()

90328888888.88889

In [10]:
df['Salary'].std()

300547.64828374365

In [11]:
df['Salary'].sum()

2480000

In [12]:
#Writing a csv (output)
df.to_csv("df_excel_practice.csv", index = False)

In [14]:
#Create array
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Create list
lis = ["India",5,6,7]
lis

['India', 5, 6, 7]

In [17]:
#Create a matrix
sample_matrix = np.matrix('1,2,3;3,4,5')
sample_matrix

matrix([[1, 2, 3],
        [3, 4, 5]])

In [18]:
#transpose matrix
np.transpose(sample_matrix)

matrix([[1, 3],
        [2, 4],
        [3, 5]])

In [19]:
#Arithmetic with matrics
sample_matrix*2
sample_matrix/2

matrix([[0.5, 1. , 1.5],
        [1.5, 2. , 2.5]])

In [20]:
#Let us learn how to create data frame
import pandas as pd
df1= pd.DataFrame({'age':[1,2,4,9],
                  'Gender':['M','F','F','M'],
                  'Income':[5,6,7,3]})

In [21]:
df1

age Gender  Income
0    1      M       5
1    2      F       6
2    4      F       7
3    9      M       3

In [22]:
#rename variable
df1=df1.rename(columns={'Gender':'Gender_v1','Income':'Income_v1'})

In [24]:
df1

age Gender_v1  Income_v1
0    1         M          5
1    2         F          6
2    4         F          7
3    9         M          3