In [3]:
# Data Science pathway:
# 1. Problem definition
# 2. Data
# 3. Evaluation
# 4. Features
# 5. Modeling
# 6. Experiments

#Numerical python- backbone of data science
# Numpy is written in C. Numpy operations are much faster than other methods.
# Performance advantage
#vectorization via broadcasting(avoiding loops)
# numbers easy to understand by computers
# Converting data into sth that machines can understand (storing in arrays)


- Most useful functions
- NumPy datatypes and attributes (ndarray)
- Creating arrays
- Viewing arrays and matrices
- Manipulating and comparing arrays
- Sorting arrays
- Use cases

In [3]:
import numpy as np

## Datatypes and Attributes

In [7]:
# NumPy main datatype is ndarray(n-dimesional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2,3.3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[10,11,12],[14,15,15],[13,14,12]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [14, 15, 15],
        [13, 14, 12]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
a1.size, a2.size, a3.size #total elements

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a data frame from a Numpy array 
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.0

## Creating arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones((2,3))

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2,3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0,10,1)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[2, 0, 0, 5, 0],
       [0, 8, 1, 0, 9],
       [7, 1, 8, 9, 5]])

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [29]:
np.random.random((5,3))

array([[0.09255298, 0.75788322, 0.80250694],
       [0.69679531, 0.23886063, 0.68527727],
       [0.9041814 , 0.67664316, 0.89255793],
       [0.48468696, 0.55362321, 0.38716957],
       [0.25456749, 0.42267033, 0.63256119]])

In [30]:
random_array_3 = np.random.rand(5,3) #axis
random_array_3

array([[0.92678299, 0.71673262, 0.55940759],
       [0.22742107, 0.32381815, 0.29585818],
       [0.95300204, 0.17142863, 0.26748424],
       [0.87242785, 0.77124383, 0.71307927],
       [0.65456312, 0.36458049, 0.4859288 ]])

In [31]:
#Pseud-random numbers
#np.random.seed()
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[1, 0, 1],
       [3, 0, 5],
       [8, 7, 7],
       [5, 4, 6],
       [8, 7, 6]])

In [32]:
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10,size = (5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## Viewing arrays and matrices 

In [33]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [14, 15, 15],
        [13, 14, 12]]])

In [37]:
a1[0]

1

In [38]:
a2.shape

(2, 3)

In [39]:
a2[0]

array([1. , 2. , 3.3])

In [40]:
a3.shape

(2, 3, 3)

a3

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [14, 15, 15],
        [13, 14, 12]]])

In [41]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [14, 15]]])

In [44]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[2, 0, 0, 5, 0],
         [0, 8, 1, 0, 9],
         [7, 1, 8, 9, 5],
         [8, 3, 4, 2, 1]],

        [[5, 5, 8, 3, 4],
         [6, 9, 6, 9, 4],
         [6, 5, 5, 8, 8],
         [7, 4, 0, 9, 2]],

        [[0, 7, 2, 8, 1],
         [2, 9, 4, 4, 4],
         [3, 3, 4, 1, 0],
         [1, 3, 0, 5, 8]]],


       [[[7, 7, 5, 4, 6],
         [8, 7, 6, 4, 7],
         [4, 4, 4, 2, 5],
         [7, 2, 2, 0, 8]],

        [[1, 5, 5, 5, 6],
         [9, 0, 7, 7, 6],
         [2, 5, 0, 9, 1],
         [0, 6, 9, 9, 3]],

        [[2, 3, 2, 4, 0],
         [6, 0, 2, 0, 6],
         [9, 5, 4, 1, 7],
         [5, 7, 8, 2, 7]]]])

In [45]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [46]:
#Getting the first 4 numbers of the inner most arrays
a4[:,:,:,:1]

array([[[[2],
         [0],
         [7],
         [8]],

        [[5],
         [6],
         [6],
         [7]],

        [[0],
         [2],
         [3],
         [1]]],


       [[[7],
         [8],
         [4],
         [7]],

        [[1],
         [9],
         [2],
         [0]],

        [[2],
         [6],
         [9],
         [5]]]])

## 4. Manipulating and comparing arrays

Arithmetic

In [47]:
a1

array([1, 2, 3])

In [48]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [49]:
a1 + ones

array([2., 3., 4.])

In [50]:
a1 - ones

array([0., 1., 2.])

In [51]:
a1 * ones

array([1., 2., 3.])

In [52]:
a1

array([1, 2, 3])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [54]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 18. ]])

In [55]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [14, 15, 15],
        [13, 14, 12]]])

In [56]:
# How can you reshape a2 to be compatible with a3?
# Search : "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [57]:
a1/ones

array([1., 2., 3.])

In [58]:
a2/a1

array([[1. , 1. , 1.1],
       [4. , 2.5, 2. ]])

In [59]:
# Floor division removes the decimals(rounds down)
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [60]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [61]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 36.  ]])

In [62]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 36.  ]])

In [63]:
a1+ones

array([2., 3., 4.])

In [64]:
np.add(a1,ones)

array([2., 3., 4.])

In [65]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [66]:
a1/2 

array([0.5, 1. , 1.5])

In [67]:
a2%2

array([[1. , 0. , 1.3],
       [0. , 1. , 0. ]])

In [68]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [69]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation 
aggregation = performing the same operation on a number of things

In [70]:
listy = [1,2,3]
type(listy)

list

In [71]:
sum(listy)

6

In [72]:
sum(a1)

6

In [73]:
np.sum(a1)

6

In [74]:
# should use pyhton methods on python data types
# and numpy arrays methods on numpy data types


In [75]:
massive = np.random.random(100000)
massive.size

100000

In [76]:
massive[:10]

array([0.64877301, 0.93911949, 0.44542119, 0.99847878, 0.66287779,
       0.67969396, 0.21406645, 0.26576971, 0.36432818, 0.23383585])

In [77]:
%timeit sum(massive)
%timeit np.sum(massive)

36.2 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
107 µs ± 1.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [78]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [80]:
np.mean(a2)

3.5500000000000003

In [81]:
np.min(a2)

1.0

In [82]:
np.std(a2)

1.6968107338965848

In [83]:
np.var(a2)

2.8791666666666664

In [84]:
np.sqrt(np.var(a2))

1.6968107338965848

## Reshaping and Transposing