In [3]:
# Data Science pathway:
# 1. Problem definition
# 2. Data
# 3. Evaluation
# 4. Features
# 5. Modeling
# 6. Experiments

#Numerical python- backbone of data science
# Numpy is written in C. Numpy operations are much faster than other methods.
# Performance advantage
#vectorization via broadcasting(avoiding loops)
# numbers easy to understand by computers
# Converting data into sth that machines can understand (storing in arrays)


- Most useful functions
- NumPy datatypes and attributes (ndarray)
- Creating arrays
- Viewing arrays and matrices
- Manipulating and comparing arrays
- Sorting arrays
- Use cases

In [4]:
import numpy as np

## Datatypes and Attributes

In [5]:
# NumPy main datatype is ndarray(n-dimesional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3.3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[10,11,12],[14,15,15],[13,14,12]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [14, 15, 15],
        [13, 14, 12]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size #total elements

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a data frame from a Numpy array 
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.0

## Creating arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2,3))

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2,3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,10,1)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[1, 9, 8, 4, 4],
       [6, 4, 1, 0, 0],
       [4, 7, 0, 2, 9]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
np.random.random((5,3))

array([[0.57289795, 0.90767011, 0.54958199],
       [0.69089741, 0.22829738, 0.33053123],
       [0.98999516, 0.00784293, 0.50461907],
       [0.84331182, 0.38754216, 0.323828  ],
       [0.45003909, 0.00398055, 0.630592  ]])

In [29]:
random_array_3 = np.random.rand(5,3) #axis
random_array_3

array([[0.89040234, 0.7311366 , 0.05219844],
       [0.5635638 , 0.94341115, 0.69119812],
       [0.0316789 , 0.80016015, 0.26152021],
       [0.72838456, 0.41001693, 0.79861186],
       [0.78150636, 0.74509025, 0.83712957]])

In [ ]:
#Pseud-random numbers
np.random.